### GENERAL SETTINGS ###

# Site settings
title: Juno
description: "Juno: iOS Jupyter client for iPhone and iPad. Connect to a notebook server with Juno and do everything you do on desktop, anywhere."
analytics: UA-104527683-1
baseurl:
url: "//juno-website-test"
image: /assets/images/open-graph.png

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more-->

# Syntax highlighting
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge

colors:  #in hex code if not noted else
  primary: "#E76817"
  blog_heading: "#E6A14A"
  primary_gradient_top: "#EA802C"
  primary_gradient_bottom: "#EBAF53"
  primary_rgb: "230,111,25" # We use RGB value here since it's needed in some places for the transparency effect.
  secondary: "#2E2A2A"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

twitter:
  username: junoclient

logo: /assets/images/open-graph.png
about: "Connect to a Jupyter/IPython server with Juno and do everything you do on desktop, anywhere. Sign up for beta now!"
author: "Alex Staravoitau"
lang: "en_GB"

email: contact@juno.sh

social:
  name: Juno
  links:
    - https://twitter.com/junoclient

webmaster_verifications:
  google: XkeGdxyWFoVT7ROPa1di7i4eGi_Pftw9YxQlaspQY3g
  bing: B3662597D7C2123E3EA94C06277B091D
  yandex: 40577c77a6506097

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/open-graph.png
